version: "3.8"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    hostname: nginx
    restart: always
    env_file:
      - .env
    ports:
      - ${MS_PORT_PUBLIC}:80
    networks:
      - frontend
      - backend
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - LARADOCK_PHP_VERSION=${PHP_VERSION}
    restart: always
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2375
      - FAKETIME=${PHP_FPM_FAKETIME}
      - LARADOCK_PHP_VERSION=${PHP_VERSION}
    depends_on:
      - workspace
    networks:
      - backend
    links:
      - docker-in-docker

  docker-in-docker:
    image: docker:dind
    privileged: true
    expose:
      - 2375
    networks:
      - backend

  workspace:
    build:
      context: .
      dockerfile: ./docker/workspace/Dockerfile
      args:
        - LARADOCK_PHP_VERSION=${PHP_VERSION}
        - SHELL_OH_MY_ZSH=${SHELL_OH_MY_ZSH}
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    tty: true
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - DOCKER_HOST=tcp://docker-in-docker:2375
    networks:
      - frontend
      - backend
    links:
      - docker-in-docker
